export interface StockInfo {
  ticker: string;
  name: string;
  sector?: string;
}

export const POPULAR_STOCKS: StockInfo[] = [
  { ticker: "AAPL", name: "Apple Inc.", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft Corporation", sector: "Technology" },
  { ticker: "GOOGL", name: "Alphabet Inc.", sector: "Communication" },
  { ticker: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Cyclical" },
  { ticker: "NVDA", name: "NVIDIA Corporation", sector: "Technology" },
  { ticker: "META", name: "Meta Platforms Inc.", sector: "Communication" },
  { ticker: "TSLA", name: "Tesla Inc.", sector: "Consumer Cyclical" },
  { ticker: "BRK-B", name: "Berkshire Hathaway Inc.", sector: "Financials" },
  { ticker: "V", name: "Visa Inc.", sector: "Financials" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { ticker: "WMT", name: "Walmart Inc.", sector: "Consumer Defensive" },
  { ticker: "JPM", name: "JPMorgan Chase & Co.", sector: "Financials" },
  { ticker: "MA", name: "Mastercard Inc.", sector: "Financials" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Defensive" },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare" },
  { ticker: "DIS", name: "The Walt Disney Co.", sector: "Communication" },
  { ticker: "HD", name: "The Home Depot Inc.", sector: "Consumer Cyclical" },
  { ticker: "BAC", name: "Bank of America Corp.", sector: "Financials" },
  { ticker: "XOM", name: "Exxon Mobil Corp.", sector: "Energy" },
  { ticker: "KO", name: "The Coca-Cola Co.", sector: "Consumer Defensive" },
  { ticker: "PEP", name: "PepsiCo, Inc.", sector: "Consumer Defensive" },
  {
    ticker: "COST",
    name: "Costco Wholesale Corporation",
    sector: "Consumer Defensive",
  },
  { ticker: "ABBV", name: "AbbVie Inc.", sector: "Healthcare" },
  { ticker: "MRK", name: "Merck & Co., Inc.", sector: "Healthcare" },
  { ticker: "AVGO", name: "Broadcom Inc.", sector: "Technology" },
  { ticker: "CVX", name: "Chevron Corporation", sector: "Energy" },
  {
    ticker: "MCD",
    name: "McDonald's Corporation",
    sector: "Consumer Cyclical",
  },
  { ticker: "CRM", name: "Salesforce, Inc.", sector: "Technology" },
  { ticker: "AMD", name: "Advanced Micro Devices, Inc.", sector: "Technology" },
  { ticker: "ACN", name: "Accenture plc", sector: "Technology" },
  { ticker: "LIN", name: "Linde plc", sector: "Basic Materials" },
  {
    ticker: "TMO",
    name: "Thermo Fisher Scientific Inc.",
    sector: "Healthcare",
  },
  { ticker: "NFLX", name: "Netflix, Inc.", sector: "Communication" },
  { ticker: "ADBE", name: "Adobe Inc.", sector: "Technology" },
  { ticker: "DHR", name: "Danaher Corporation", sector: "Healthcare" },
  { ticker: "PFE", name: "Pfizer Inc.", sector: "Healthcare" },
  { ticker: "NKE", name: "NIKE, Inc.", sector: "Consumer Cyclical" },
  {
    ticker: "TXN",
    name: "Texas Instruments Incorporated",
    sector: "Technology",
  },
  {
    ticker: "PM",
    name: "Philip Morris International Inc.",
    sector: "Consumer Defensive",
  },
  { ticker: "INTC", name: "Intel Corporation", sector: "Technology" },
  {
    ticker: "VZ",
    name: "Verizon Communications Inc.",
    sector: "Communication",
  },
  { ticker: "CMCSA", name: "Comcast Corporation", sector: "Communication" },
  { ticker: "NEE", name: "NextEra Energy, Inc.", sector: "Utilities" },
  { ticker: "WFC", name: "Wells Fargo & Company", sector: "Financials" },
  { ticker: "ORCL", name: "Oracle Corporation", sector: "Technology" },
  { ticker: "QCOM", name: "QUALCOMM Incorporated", sector: "Technology" },
  {
    ticker: "HON",
    name: "Honeywell International Inc.",
    sector: "Industrials",
  },
  { ticker: "COP", name: "ConocoPhillips", sector: "Energy" },
  { ticker: "RTX", name: "RTX Corporation", sector: "Industrials" },
  {
    ticker: "IBM",
    name: "International Business Machines",
    sector: "Technology",
  },
  { ticker: "BA", name: "The Boeing Company", sector: "Industrials" },
  { ticker: "GE", name: "General Electric Company", sector: "Industrials" },
  {
    ticker: "SBUX",
    name: "Starbucks Corporation",
    sector: "Consumer Cyclical",
  },
  { ticker: "GS", name: "The Goldman Sachs Group, Inc.", sector: "Financials" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financials" },
  { ticker: "BLK", name: "BlackRock, Inc.", sector: "Financials" },
  { ticker: "C", name: "Citigroup Inc.", sector: "Financials" },
  { ticker: "T", name: "AT&T Inc.", sector: "Communication" },
  { ticker: "INTU", name: "Intuit Inc.", sector: "Technology" },
  { ticker: "UNP", name: "Union Pacific Corporation", sector: "Industrials" },
  { ticker: "AMGN", name: "Amgen Inc.", sector: "Healthcare" },
  { ticker: "MDT", name: "Medtronic plc", sector: "Healthcare" },
  {
    ticker: "LOW",
    name: "Lowe's Companies, Inc.",
    sector: "Consumer Cyclical",
  },
  { ticker: "SPGI", name: "S&P Global Inc.", sector: "Financials" },
  { ticker: "CAT", name: "Caterpillar Inc.", sector: "Industrials" },
  { ticker: "NOW", name: "ServiceNow, Inc.", sector: "Technology" },
  { ticker: "LMT", name: "Lockheed Martin Corporation", sector: "Industrials" },
  { ticker: "UBER", name: "Uber Technologies, Inc.", sector: "Technology" },
  { ticker: "PLTR", name: "Palantir Technologies Inc.", sector: "Technology" },
  { ticker: "SNOW", name: "Snowflake Inc.", sector: "Technology" },
  { ticker: "CRWD", name: "CrowdStrike Holdings, Inc.", sector: "Technology" },
  { ticker: "SHOP", name: "Shopify Inc.", sector: "Technology" },
  { ticker: "SQ", name: "Block, Inc.", sector: "Financials" },
  { ticker: "PYPL", name: "PayPal Holdings, Inc.", sector: "Financials" },
  { ticker: "COIN", name: "Coinbase Global, Inc.", sector: "Financials" },
  { ticker: "SOFI", name: "SoFi Technologies, Inc.", sector: "Financials" },
  { ticker: "HOOD", name: "Robinhood Markets, Inc.", sector: "Financials" },

  // Popular ETFs
  {
    ticker: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    sector: "ETF - Large Blend",
  },
  { ticker: "QQQ", name: "Invesco QQQ Trust", sector: "ETF - Large Growth" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF", sector: "ETF - Large Blend" },
  {
    ticker: "VTI",
    name: "Vanguard Total Stock Market ETF",
    sector: "ETF - Large Blend",
  },
  {
    ticker: "DIA",
    name: "SPDR Dow Jones Industrial Average ETF",
    sector: "ETF - Large Value",
  },
  {
    ticker: "SCHD",
    name: "Schwab US Dividend Equity ETF",
    sector: "ETF - Large Value",
  },
  {
    ticker: "VYM",
    name: "Vanguard High Dividend Yield ETF",
    sector: "ETF - Large Value",
  },
  {
    ticker: "JEPI",
    name: "JPMorgan Equity Premium Income ETF",
    sector: "ETF - Options",
  },
  {
    ticker: "JEPQ",
    name: "JPMorgan Nasdaq Equity Premium Income ETF",
    sector: "ETF - Options",
  },
  { ticker: "VUG", name: "Vanguard Growth ETF", sector: "ETF - Large Growth" },
  { ticker: "VTV", name: "Vanguard Value ETF", sector: "ETF - Large Value" },
  { ticker: "ARKK", name: "ARK Innovation ETF", sector: "ETF - Mid Growth" },
  { ticker: "SOXX", name: "iShares Semiconductor ETF", sector: "ETF - Tech" },
  {
    ticker: "XLK",
    name: "Technology Select Sector SPDR",
    sector: "ETF - Tech",
  },
  {
    ticker: "XLF",
    name: "Financial Select Sector SPDR",
    sector: "ETF - Financials",
  },
  {
    ticker: "XLV",
    name: "Health Care Select Sector SPDR",
    sector: "ETF - Healthcare",
  },
  { ticker: "XLE", name: "Energy Select Sector SPDR", sector: "ETF - Energy" },
  {
    ticker: "TLT",
    name: "iShares 20+ Year Treasury Bond ETF",
    sector: "ETF - Long Govt",
  },
  {
    ticker: "BND",
    name: "Vanguard Total Bond Market ETF",
    sector: "ETF - Interm Core",
  },
  { ticker: "GLD", name: "SPDR Gold Shares", sector: "ETF - Commodities" },

  // ─── Thai Stocks (SET .BK) ───
  { ticker: "PTT.BK", name: "ปตท. (PTT PCL)", sector: "พลังงาน" },
  { ticker: "AOT.BK", name: "ท่าอากาศยานไทย (AOT)", sector: "บริการ" },
  { ticker: "CPALL.BK", name: "ซีพี ออลล์ (CP ALL)", sector: "ค้าปลีก" },
  { ticker: "SCC.BK", name: "ปูนซิเมนต์ไทย (SCG)", sector: "วัสดุก่อสร้าง" },
  { ticker: "ADVANC.BK", name: "แอดวานซ์ อินโฟร์ (AIS)", sector: "สื่อสาร" },
  { ticker: "KBANK.BK", name: "ธ.กสิกรไทย (KBank)", sector: "ธนาคาร" },
  { ticker: "SCB.BK", name: "ธ.ไทยพาณิชย์ (SCB)", sector: "ธนาคาร" },
  { ticker: "BBL.BK", name: "ธ.กรุงเทพ (BBL)", sector: "ธนาคาร" },
  { ticker: "KTB.BK", name: "ธ.กรุงไทย (KTB)", sector: "ธนาคาร" },
  { ticker: "TTB.BK", name: "ธ.ทหารไทยธนชาต (TTB)", sector: "ธนาคาร" },
  { ticker: "GULF.BK", name: "กัลฟ์ เอ็นเนอร์จี (GULF)", sector: "พลังงาน" },
  {
    ticker: "DELTA.BK",
    name: "เดลต้า อีเลคโทรนิคส์ (DELTA)",
    sector: "อิเล็กทรอนิกส์",
  },
  { ticker: "BDMS.BK", name: "กรุงเทพดุสิตเวชการ (BDMS)", sector: "สุขภาพ" },
  { ticker: "BH.BK", name: "โรงพยาบาลบำรุงราษฎร์ (BH)", sector: "สุขภาพ" },
  {
    ticker: "MINT.BK",
    name: "ไมเนอร์ อินเตอร์เนชั่นแนล (MINT)",
    sector: "ท่องเที่ยว",
  },
  { ticker: "CPN.BK", name: "เซ็นทรัลพัฒนา (CPN)", sector: "อสังหาริมทรัพย์" },
  { ticker: "TRUE.BK", name: "ทรู คอร์ปอเรชั่น (TRUE)", sector: "สื่อสาร" },
  { ticker: "BEM.BK", name: "ทางด่วนและรถไฟฟ้า (BEM)", sector: "ขนส่ง" },
  { ticker: "GPSC.BK", name: "โกลบอลเพาเวอร์ (GPSC)", sector: "พลังงาน" },
  { ticker: "IVL.BK", name: "อินโดรามา เวนเจอร์ส (IVL)", sector: "ปิโตรเคมี" },
  { ticker: "HMPRO.BK", name: "โฮมโปร (HomePro)", sector: "ค้าปลีก" },
  {
    ticker: "PTTGC.BK",
    name: "พีทีที โกลบอล เคมิคอล (PTTGC)",
    sector: "ปิโตรเคมี",
  },
  { ticker: "PTTEP.BK", name: "ปตท.สผ. (PTTEP)", sector: "พลังงาน" },
  { ticker: "OR.BK", name: "ปตท. น้ำมันและการค้าปลีก (OR)", sector: "พลังงาน" },
  { ticker: "EA.BK", name: "พลังงานบริสุทธิ์ (EA)", sector: "พลังงานทดแทน" },
  { ticker: "BANPU.BK", name: "บ้านปู (BANPU)", sector: "พลังงาน" },
  {
    ticker: "SAWAD.BK",
    name: "ศรีสวัสดิ์ คอร์ปอเรชั่น (SAWAD)",
    sector: "การเงิน",
  },
  { ticker: "MTC.BK", name: "เมืองไทย แคปปิตอล (MTC)", sector: "การเงิน" },
  { ticker: "BJC.BK", name: "เบอร์ลี่ ยุคเกอร์ (BJC)", sector: "ค้าปลีก" },
  {
    ticker: "WHA.BK",
    name: "ดับบลิวเอชเอ คอร์ปอเรชั่น (WHA)",
    sector: "อสังหาริมทรัพย์",
  },
  { ticker: "TISCO.BK", name: "ธ.ทิสโก้ (TISCO)", sector: "ธนาคาร" },
  { ticker: "OSP.BK", name: "โอสถสภา (OSP)", sector: "อาหารเครื่องดื่ม" },
  { ticker: "CBG.BK", name: "คาราบาว กรุ๊ป (CBG)", sector: "อาหารเครื่องดื่ม" },

  // ─── Thai ETFs ───
  { ticker: "THAIETH.BK", name: "กองทุน SET50 ETF", sector: "ETF ไทย" },
  { ticker: "ENGY.BK", name: "กองทุน Energy ETF", sector: "ETF ไทย - พลังงาน" },
  { ticker: "GLD.BK", name: "กองทุน Gold ETF", sector: "ETF ไทย - ทองคำ" },
];
